# -*- coding: utf-8 -*-
"""DummyClassifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RJTtBDnJEgLPGHI1vXsdGcUUP6zlemtM

# Import Data
"""

url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names=['sepel-length', 'sepel-width', 'petal-length', 'patel-width', 'Class']

import pandas as pd
dataset = pd.read_csv(url, names=names)

"""Understanding the dataset"""

dataset.head()
dataset['Class'].value_counts()
dataset.shape
dataset.info()

"""# Data Preprocessing"""

Data=dataset.iloc[:,:4]
Label=dataset.iloc[:,-1]

"""# Model Training"""

from sklearn.dummy import DummyClassifier

model = DummyClassifier()
model.fit(Data,Label)

"""Model Prediction"""

prediction = model.predict(Data)

"""# Model Evaluation"""

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Label.values, prediction)
accuracy